[package]
name = "exchage"
description = "A commandline tool converting currencies"
version = "0.1.0"
license = "MIT"
authors = ["Chun-wei Kuo <Dendoh@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "^0.9.20"
